version: '2'
services:
    web:
        build:
            context: ./
            dockerfile: docker/web.docker
        volumes:
            - ./:/var/www
            - ./docker/logs/nginx/nginx-error.log:/var/log/nginx/error.log
            - ./docker/logs/nginx/nginx-access.log:/var/log/nginx/access.log
        ports:
            - "8000:80"
        links:
            - app
    app:
        build:
            context: ./
            dockerfile: docker/app.docker
        volumes:
            - ./:/var/www
        links:
            - database
    database:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: root
            MYSQL_DATABASE: stockopedia
            MYSQL_USER: root
        ports:
            - "30006:3306"
        volumes:
            - ./docker/mysql:/var/lib/mysql
